### ISSUE TITLE
Ajustes reloj mi 9 se miui 11

### ISSUE THREAD

**Issue by pantxi11** [ingbrzy/MA-XML-11-SPANISH#2]
vMiui 11.0.3 estable
Hay algunos ajustes del reloj que estan en inglés, y del menu "informe de la mañana" de la misma app.

![Screenshot_2019-11-06-22-54-26-229_com android deskclock](https://user-images.githubusercontent.com/48735062/68341962-da6a4900-00e9-11ea-96b0-b671d482b8c1.jpg)

![Screenshot_2019-11-06-23-05-33-734_com android deskclock](https://user-images.githubusercontent.com/48735062/68342040-04bc0680-00ea-11ea-85e9-d531e335d9b4.jpg)

**Comment by danielchc** [comment]
Hola, gracias por avisar para la próxima versión debería estar solucionado
