### ISSUE TITLE
Me gustaria ayudar con las traducciones

### ISSUE THREAD

**Issue by nmercy-arg** [ingbrzy/MA-XML-11-SPANISH#8]
Cree la issue como decia el Readme.

Saludos!

**Comment by Davidjarod11** [comment]
Creo que deberías contactar directamente con los que dirigen Xiaomi.eu

**Comment by danielchc** [comment]
Hola, actualmente no hay nadie traduciendo la rom. Hasta hace unos meses era solo yo y debido a que ahora no tengo tiempo no puedo ayudar a traducir.
Lo que puedes hacer es ir haciendo pull requests para traducir las cadenas que faltan

**Comment by danielchc** [comment]
Duplicate of #11

**Comment by danielchc** [comment]
continuamos hablando en la #11
